
  
sudo: required

services:
  - docker
  
language: go

go:
  - "1.10.x"
  - "1.11.x"

before_script:
  - git clone "https://github.com/TheCacophonyProject/cacophony-api"
  - cd cacophony-api
  - ./run --isolate --background
  - cd ..
script:
  - go vet ./... && go test ./...
