
  
sudo: required

services:
  - docker
  
language: go

go:
  - "1.10.x"
  - "1.11.x"

before_script:
  - git clone "https://github.com/TheCacophonyProject/cacophony-api"
  - cd cacophony-api
  - ./run --isolate --background
  - cd ..
  - ls
  - docker cp db-test-seed.sql cacophony-api:/db-seed.sql
  - sudo docker exec -it cacophony-api bash
  - sudo -i -u postgres psql cacophonytest -f/db-seed.sql
  - exit
script:
  - go vet ./... && go test ./...
