
  
sudo: required

services:
  - docker
  
language: go

go:
  - "1.10.x"
  - "1.11.x"

before_script:
  - git clone "https://github.com/TheCacophonyProject/cacophony-api"
  - .cacophony-api/run --isolate --background
script:
  - go vet ./... && go test ./...
